### PR TITLE
Add FileDriver to write emails to filesystem

### PR DESCRIPTION
**Pull request by mattstrayer**
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce?

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/adonisjs/mail/blob/master/.github/CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by thetutlage** [comment]
Is there any specific use case the file driver will serve?

**Comment by mattstrayer** [comment]
@thetutlage it is very helpful during development. Writing emails to the file system allows for easy inspection of the rendered html & all relevant message info. The idea was inspired by Django. https://docs.djangoproject.com/en/4.1/topics/email/#obtaining-an-instance-of-an-email-backend 

image



Here's an example of how I use it in my basemailer class

`public mailer = Application.inDev ? Mail.use('file') : Mail.use('smtp')`

**Comment by thetutlage** [comment]
If this is solely for development, then I highly recommend looking into Mailhog. https://github.com/mailhog/MailHog.

You just have to use Mailhog SMTP credentials and then view emails in their browser based email client. This way, you can not only view the text of the email, but also the attachments or embedded images.

**Comment by mattstrayer** [comment]
@thetutlage 

Totally agree that MailHog is a **great** tool to have in the tool belt. I also think that there's a place for the file driver to coexist. It is nice to have a solution to see that an email is being sent and the contents of that email without having to rely on any third party services being installed or running.

**Comment by Julien-R44** [comment]
Thanks for your PR ! but after talking about it together none of us would use it. We use Mailhog / mailpit all the time so we don't feel like integrating it into the repo because it would mean maintaining a piece of code that we don't use

**Pull request closed without merging**
